server:
  port: 8800
  address: windowHost #启动服务地址
spring:
  application:
    name: cloud-client #为你的应用起个名字，该名字将注册到eureka注册中心
eureka:
  instance:
    statusPageUrlPath: ${management.context-path}/info
    healthCheckUrlPath: ${management.context-path}/health
  client:
    serviceUrl:
      defaultZone: http://windowHost:8761/eureka/ #去哪里注册，eureka服务地址
